inherit_gem:
  rubocop-config-crystal: .rubocop.yml

plugins:
  - rubocop-rspec

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MissingExpectationTargetMethod:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Lint/MissingSuper:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Enabled: false
